function peliculas() {

    var lista = [
      'POR SIEMPRE CENICIENTA (1998 - Drew Barrymore; Dougray Scott)' , 
      'BUENA GENTE (2014 – James Franco; Kate Hudson)' , 
      'AMOR EN JUEGO (2005 - Jimmy Fallon; Drew Barrymore)' , 
      'JAMÁS BESADA (1999 - Drew Barrymore; David Arquette)' , 
      'DÚPLEX (2003 - Ben Stiller; Drew Barrymore)' , 
      'TODOS ESTÁN BIEN (2009 - Robert De Niro; Drew Barrymore)' , 
      'LUNA DE MIEL EN FAMILIA (2014 - Adam Sandler; Drew Barrymore)' , 
      'COMO PERROS Y GATOS (2001 - Jeff Goldblum; Elizabeth Perkins)' , 
      'SIEMPRE EL MISMO DÍA (2011 - Anne Hattaway; Jim Sturgess)' , 
      'VIRGEN A LOS 40 (2005 - Steve Carrell; Paul Rudd)' , 
      'EL GRITO (2004 – Sarah Gellard; Jason Behr)' , 
      'EL JUEGO DEL MIEDO (2004 - Leigh Whannell; Cary Elwes)' , 
      'CONTAGIO (2011 – Matt Damon; Kate Winslet; Jude Law)' , 
      'LA LLAMADA (2002 - Naomi Watts; Martin Henderson)' , 
      'COMO PERDER A UN HOMBRE EN 10 DÍAS (2003 - Matthew McConaughey; Kate Hudson)' , 
      'MÚJERES AL ATAQUE (2014 - Cameron Díaz; Nicky Minaj)' , 
      'GUERRA DE NOVIAS (2009 - Kate Hudson; Anne Hattaway)' , 
      'EL ORIGEN (2010 - Leonardo Di Caprio; Ellen Page; Cillian Murphy)' , 
      'LA RED SOCIAL (2010 – Justin Timberlake; Armie Hammer; Andrew Garfield)' , 
      'LOS 4 FANTÁSTICOS (2005 - Jessica Alba; Chris Evans)' , 
      'LICENCIA PARA MATAR (1989 – Benicio Del Toro; Carey Lowell)' , 
      'DURO DE MATAR (1988 - Bruce Willis; Alan Rickman)' , 
      'MEDIANOCHE EN PARÍS (2011 - Owen Wilson; Rachel McAdams; Marion Cotillard; Adrien Brody)' , 
      'NÁUFRAGO (2000 - Tom Hanks; Helen Hunt)' , 
      'ACTIVIDAD PARANORMAL (2007 - Catie Featherston; Micah Sloat)' , 
      'PIRATAS DEL CARIBE (2003 - Johnny Depp; Orlando Bloom; Keira Knightley)' , 
      'NUEVE REINAS (2000 - Ricardo Darín; Gastón Pauls; Tomás Fonsi; Leticia Bredice)' , 
      'EL TURISTA (2010 – Johnny Depp; Angelina Jolie; Paul Bettany)' , 
      'SIN LÍMITES (2011 - Bradley Cooper; Robert De Niro)' , 
      'EL FRANCOTIRADOR (2014 – Bradley Cooper; Sienna Miller)' , 
      'SHREK (2001 - Eddie Murphy; Cameron Díaz; Antonio Banderas)' , 
      'EL HOMBRE ARAÑA (2002 - Toby McGuire; Kirsten Dunst; James Franco)' , 
      'LAS TORTUGAS NINJAS (2014 – Megan Fox; Pete Plozek)' , 
      'SUPERMAN (2013 – Henry Cavill; Amy Adams; Russell Crowe; Kevin Costner)' , 
      'EL FANTASMA DE LA ÓPERA (2004 – Gerard Butler; Emmi Rossum; Patrick Wilson)' , 
      'VIERNES 13 (2009 – Jared Padalecki; Danielle Panavaker)' , 
      'YO, ROBOT (2004 - Will Smith; Bruce Greenwood; Shia LaBeouf)' , 
      'PERFUME DE MUJER (1992 – Al Pacino; Phillip Seymour)' , 
      'EL PERFUME (2006 – Dustin Hoffman; Ben Whishaw)' , 
      'NOCHES BLANCAS (2002 – Al Pacino; Robin Williams; Hillary Swank)' , 
      'UNA NOCHE EN EL MUSEO (2006 – Ben Stiller; Robin Williams; Owen Wilson)' , 
      'LA GUERRA DE LAS GALAXIAS (1977 – Harrison Ford; Mark Hamill)' , 
      'LA VIDA ES BELLA (1997 – Robert Benigni; Nicoletta Braschi)' , 
      'EL REY LEÓN (1994 – Matthew Broderic; Jeremy Irons)' , 
      'LO QUE EL VIENTO SE LLEVÓ (1939 – Clark Gable; Vivien Leigh)' , 
      'DESTINO FINAL (2000 - Tony Todd; Ali Larter)' , 
      '12 AÑOS DE ESCLAVITUD (2003 – Brad Pitt; Lupita Nyong’o; Chiwetel Ejiofor)' , 
      'LA LADRONA DE LIBROS (2013 – Sophie Nelisse; Emily Watson; Geoffrey Rush)' , 
      'EL PLANETA DEL TESORO (2002 – Joseph Gordon; Emma Thompson)' , 
      'LEYENDAS DE PASIÓN (1994 - Brad Pitt; Anthony Hopkins)' , 
      'IRONMAN (2008 - Robert Downey Jr; Gwyneth Paltrow)' , 
      'LETRA Y MÚSICA (2007 - Hugh Grant; Drew Barrymore)' , 
      'SHERLOCK HOLMES (2009 - Robert Downey Jr; Jude Law; Rachel McAdams)' , 
      'CAPITÁN AMÉRICA (2011 - Chris Evans; Samuel Jackson)' , 
      'AMIGOS CON DERECHOS (2011 - Ashton Kutcher; Natalie Portman)' , 
      'AGUA PARA ELEFANTES (2011 – Reese Witherspoon; Robert Pattinson)' , 
      'CABALLO DE GUERRA (2011 – Emily Watson; Jeremy Irvine)' , 
      'LOCO Y ESTÚPIDO AMOR (2011 - Steve Carell; Ryan Gosling; Emma Stone; Julianne Moore)' , 
      'TODOPODEROSO (2003 – Jim Carrey; Morgan Freeman; Jennifer Aniston; Steve Carell)' , 
      'COMO SI FUERA LA PRIMERA VEZ (2004 - Drew Barrymore; Adam Sandler)' , 
      'CRÍADAS Y SEÑORAS (2011 - Emma Stone; Octavia Spencer)' , 
      'LA NOCHE DEL DEMONIO (2010 – Patrick Wilson; Rose Byrne)' , 
      'REALMENTE AMOR (2003 – Hugh Grant; Liam Neeson; Colin Firth; Keira Knightley)' , 
      'EL JUEZ (2014 – Robert Downey Jr; Robert Duvall)' , 
      'EL CLUB DE LA PELEA (1999 – Edward Norton; Brad Pitt)' , 
      'PERDIDA (2014 – Ben Affleck; Rosamund PIke)' , 
      'LA CUEVA (2014 – Marta Castellote; Xoel García)' , 
      'TONTO Y RETONTO (1994 - Jim Carrey; Jeff Daniels)' , 
      'LAZOS PERVERSOS (2013 – Mia Wasikowska; Matthew Goode; Nicole Kidman)' , 
      'LA MÁSCARA (1994 – Jim Carrey; Cameron Díaz)' , 
      'NUESTRO VIDEO PROHIBIDO (2014 - Cameron Díaz; Jason Segel)' , 
      'EL SILENCIO DE LOS INOCENTES (1991 - Anthony Hopkins; Jodie Foster)' , 
      'ATRÁPAME SI PUEDES (2002 – Leonardo Di Caprio; Tom Hanks)' , 
      'SIMPLEMENTE NO TE QUIERE (2009 – Ben Affleck; Jennifer Aniston; Drew Barrymore;)' , 
      'BAJO LA MISMA ESTRELLA (2014 – Shailene Woodley; Ansel Elgort)' , 
      'UNA AVENTURA EXTRAORDINARIA (2012 – Suraj Sharma; Irrfan Khan)' , 
      'LA VUELTA AL MUNDO EN 80 DÍAS (2004 – Jackie Chan; Steve Coghan)' , 
      'LAS INSOLADAS (2014 – Carla Peterson; Luisana Lopilato)' , 
      'MÚSICA EN ESPERA (2009 - Natalia Oreiro;  Diego Peretti)' , 
      'PALABRAS ROBADAS (2012 – Bradley Cooper; Zoe Saldana)' , 
      'ESPERANDO LA CARROZA (1985 – China Zorrilla; Antonio Gasalla; Luis Brandoni)' , 
      '2 + 2 (2012 – Adrián Suar; Carla Petterson; Julieta Díaz; Juan Minujín)' , 
      'LOS VENGADORES (2012 – Robert Downey Jr; Chris Evans; Mark Ruffalo; Chris Hemsworth)' , 
      'TED (2012 – Mark Wahlberg; Mila Kunis)' , 
      'VALIENTE (2012 – Emma Thompson; Billy Connolly)' , 
      'CORAZÓN VALIENTE (1995 – Mel Gibson; Sophie Marceau)' , 
      'LA DAMA DE HIERRO (2012 – Meryl Streep; Jim Broadbent)' , 
      'BUENOS VECINOS (2015 – Seth Rogen; Zac Efron)' , 
      'PAPÁ POR ACCIDENTE (2010 – Jennifer Aniston; Jason Bateman)' , 
      'PROYECTO X (2012 – Thomas Mann; Oliver Cooper)' , 
      'LA NARANJA MECÁNICA (1971 – Malcolm McDowell; Warren Clarke)' , 
      'EL SECRETO DE SUS OJOS (2009 – Ricardo Darín; Soledad Villamil; Guillermo Francella)' , 
      'HIJO DE DIOS (2014 – Diogo Morgado; Roma Downey)' , 
      'RECUÉRDAME (2010 – Robert Pattinson; Emilie De Ravin; Pierce Brosnan)' , 
      'CARTAS A JULIETA (2010 – Amanda Seyfried; Christopher Egan)' , 
      '3 DÍAS PARA MATAR (2014 – Kevin Costner; Amber Heard)' , 
      'LAS NOVIAS DE MIS AMIGOS (2014 – Zac Efron; Miles Teller)' , 
      'BAJO EL MISMO TECHO (2010 – Katherine Heigl; Josh Duhamel; Josh Lucas)' , 
      'LA DUDA (2008 – Meryl Streep; Philip Seymour; Amy Adams)' , 
      'EL DIABLO SE VISTE A LA MODA (2006 – Meryl Streep; Anne Hathaway; Emily Blunt)' , 
      'EL DÍA DESPUÉS DE MAÑANA (2004 – Dennis Quaid; Jake Gyllenhaal)' , 
      'EL CÓDIGO DA VINCI (2006 – Tom Hanks; Audrey Tautou; Paul Bettany)' , 
      'DÍA DE LA INDEPENDENCIA (1996 – Will Smith; Jeff Goldblum)' , 
      'ANTES DEL AMANECER (1995 – Ethan Hawke; Julie Delpy)' , 
      '127 HORAS (2011 – James Franco; Aaron Ralston)' , 
      'BATMAN: EL CABALLERO DE LA NOCHE (2008 – Christian Bale; Heath Ledger; Michael Caine)' , 
      'ALICIA EN EL PAÍS DE LAS MARAVILLAS (2010 – Johnny Depp; Anne Hathaway)' , 
      'ÁNGELES Y DEMONIOS (2009 – Tom Hanks; Ewan Mc Gregor)' , 
      'EL RITO (2011 – Anthony Hopkins; Alice Braga)' , 
      'EL ABOGADO DEL DIABLO (1997 – Keanu Reeves; Al Pacino; Charlize Theron)' , 
      'LEGALMENTE RUBIA (2001 – Reese Witherspoon; Luke Wilson)' , 
      'MÁS ALLÁ DE LAS FRONTERAS (2003 – Angelina Jolie; Clive Owen)' , 
      'MÁS ALLÁ DEL CIELO (2010 – Zac Efron; Kim Basinger)' , 
      'CISNE NEGRO (2012 – Natalie Portman; Mila Kunis; Winona Ryder)' , 
      'EL BUEN PASTOR (2006 – Robert De Niro; Matt Damon; Angelina Jolie)' , 
      'LA MOMIA (1999 – Brendan Fraser; Rachel Weisz)' , 
      'EL JARDINERO FIEL (2005 – Rachel Weisz; Ralph Fiennes)' , 
      'EL MAYORDOMO (2013 – Oprah Winfrey; Forest Whitaker; Robin Williams)' , 
      'EL HOMBRE LOBO (2010 – Benicio del Toro; Emily Blunt; Anthony Hopkins)' , 
      'EL NIÑO CON EL PIJAMA DE RAYAS (2008 – Asa Butterfield; David Thewlis)' , 
      'MISIÓN IMPOSIBLE (1996 – Tom Cruise; Jon Voight)' , 
      'GODZILLA (1998 – Matthew Broderick; Jean Reno)' , 
      'GUERRA MUNDIAL “Z” (2013 – Brad Pitt; Mireille Enos)' , 
      'BASTARDOS SIN GLORIA (2009 – Quentin Tarantino; Brad Pitt; Diane Kruger)' , 
      'LA ERA DEL HIELO (2002)' , 
      'EL LUCHADOR (2008 – Mickey Rourke; Marisa Tomei)' , 
      'UNA MENTE BRILLANTE (2001 – Russell Crowe; Ed Harris; Jennifer Connelly)' , 
      'LO IMPOSIBLE (2012 – Naomi Watts; Ewan Mc Gregor)' , 
      'CORRER O MORIR (2014 – Dylan O’Brien; Kaya Scodelario)' , 
      'JUMANJI (1995 – Robin Williams; Kirsten Dunst)' , 
      'VOTOS DE AMOR (2012 – Rachel McAdams; Channing Tatum)' , 
      'MUJER BONITA (1990 – Julia Roberts; Richard Gere)' , 
      'EL VIENTO QUE ACARICIA EL PRADO (2006 – Cillian Murphy; Liam Cunningham)' , 
      'TESIS SOBRE UN HOMICIDIO (2013 – Ricardo Darín; Calu Rivero; Arturo Puig)' , 
      'EL AURA (2005 – Ricardo Darín; Dolores Fonzi)' , 
      'CAMINO A LA LIBERTAD (2010 – Colin Farrell; Jim Sturgess; Ed Harris)' , 
      'VUELO NOCTURNO (2005 – Rachel McAdams; Cillian Murphy)' , 
      'PLAN DE VUELO (2005 – Jodie Foster; Sean Bean)' , 
      'SECRETO EN LA MONTAÑA (2005 – Heath Ledger; Jake Gyllenhaal)' , 
      'MI VILLANO FAVORITO (2010)' , 
      'EL LADO BUENO DE LAS COSAS (2012 – Bradley Cooper; Jennifer Lawrence; Robert De Niro)' , 
      'RÁPIDO Y FURIOSO (2001 – Paul Walker; Vin Diesel)' , 
      'EL CONJURO (2013 – Patrick Wilson; Vera Farmiga)' , 
      'THOR (2011 – Chris Hemsworth; Natalie Portman)' , 
      'EL LLANERO SOLITARIO (2013 – Johnny Depp; Armie Hammer; Helena Bonham Carter)' , 
      'EL ATAQUE (2013 – Channing Tatum; Jamie Foxx)' , 
      'LA HUESPED (2013 – Saoirse Ronan; Max Irons)' , 
      'LA PURGA (2013 – Ethan Hawke; Lena Headey)' , 
      'UNA LOCA PELÍCULA ÉPICA (2007 – Jayma Mays; Kal Penn)' , 
      '27 BODAS (2008 – Katherine Heigl; James Marsden; Edward Burns)' , 
      'EL ILUSIONISTA (2006 – Edward Norton; Jessica Biel; Rufus Sewell)' , 
      'LA GRAN ESTAFA (2001 – George Clooney; Brad Pitt; Matt Damon; Julia Roberts)' , 
      'EL GRAN TRUCO (2006 – Christian Bale; Hugh Jackman; Scarlett Johansson)' , 
      'EL PADRINO (1972 – Al Pacino; Marlon Brando; Robert Duvall; Diane Keaton)' , 
      'GLADIADOR (2000 – Russell Crowe; Joaquin Phoenix)' , 
      'REGRESO AL FUTURO (1985 – Michael Fox; Christopher Lloyd)' , 
      '“V” DE VENGANZA (2006 – Natalie Portman; Hugo Weaving)' , 
      'EL CLUB DE LA PELEA (1999 – Brad Pitt; Edward Norton; Jared Leto)' , 
      'PARQUE JURÁSICO (1993 – Jeff Goldblum; Sam Neil; Laura Dern)' , 
      'EL EXORCISTA (1973 – Linda Blair; Max von Sydow)' , 
      'HOMBRES DE NEGRO (1997 – Will Smith; Tommy Lee Jones)' , 
      'BUSCANDO A NEMO (2003 – Ellen DeGeneres; Willem Dafoe)' , 
      'BÚSQUEDA IMPLACABLE (2008 – Liam Neeson; Famke Janssen)' , 
      'LA LEYENDA DEL TESORO PERDIDO (2004 – Nicolas Cage – Diane Kruger)' , 
      'SIN MOTIVO APARENTE (2014 – Idris Elba; Taraji Henson)' , 
      'CAMINANDO ENTRE TUMBAS (2014 – Liam Neeson; Dan Stevens)' , 
      'SIN ESCALA (2014 – Liam Neeson; Julianne Moore)' , 
      'ROBANDO VIDAS (2004 – Angelina Jolie; Ethan Hawke)' , 
      'RELATOS SALVAJES (2015 – Ricardo Darín; Erica Rivas; Leonardo Sbaraglia)' , 
      'LOS JUEGOS DEL HAMBRE (2008 – Jennifer Lawrence; Josh Hutcherson; Liam Hemsworth)' , 
      'EL JUSTICIERO (2014 – Denzel Washington; David Harbour)' , 
      'HULK (2003 – Eric Bana; Jennifer Connelly)' , 
      'LA EMBOSCADA (1999 – Sean Connery; Catherine Zeta-Jones)' , 
      'LA ROCA (1996 – Nicolas Cage; Sean Connery; Ed Harris)' , 
      'SIN RESERVAS (2007 – Catherine Zeta-Jones; Aaron Eckhart)' , 
      '500 DÍAS CON ELLA (2009 – Zooey Deschanel; Joseph Gordon-Lee)' , 
      'EL ÚNICO SOBREVIVIENTE (2013 – Mark Wahlberg; Eric Bana)' , 
      'LA LEY DEL MÁS FUERTE (2013 – Christian Bale; Casey Affleck; Woody Harrelson)' , 
      'EL SEÑOR DE LA GUERRA (2005 – Nicolas Cage; Jared Leto; Ethan Hawke)' , 
      'LA SOSPECHA (2013 – Hugh Jackman; Jake Gyllenhaal; María Bello)' , 
      'LA FURIA DE LA MONTAÑA (1997 – Pierce Brosnan; Linda Hamilton)' , 
      'LA BELLA Y LA BESTIA (1991)' , 
      'CELULAR (2004 – Chris Evans; Kim Basinger)' , 
      'DESPUÉS DE LA TIERRA (2013 – Will Smith; Jaden Smith)' , 
      'P.D. TE AMO (2007 – Gerard Butler – Hilary Swank)' , 
      'LA DECISIÓN MÁS DIFICIL (2009 – Cameron Díaz – Alec Baldwin)' , 
      'EL GATO CON BOTAS (2011 – Antonio Banderas; Salma Hayek; Zach Galifianakis)' , 
      'EL CUERPO (2012 – Belén Rueda; Hugo Silva)' , 
      'LA MALDICIÓN (2004 – Christina Ricci; Jesse Eisenberg)' , 
      'PAPÁ POR SIEMPRE (1993 – Robin Williams; Sally Field)' , 
      'MI POBRE ANGELITO (1990 – Macaulay Culkin; Catherine O’hara)' , 
      'LOS MISERABLES (2012 – Anne Hathaway; Hugh Jackman; Russell Crowe; Amanda Seyfried)' , 
      'SIETE AÑOS EN EL TIBET (1997 – Brad Pitt; David Thewlis)' , 
      'AHORA Y SIEMPRE (2012 – Dakota Fanning; Jeremy Irvine)' , 
      'SE LO QUE HICISTE EL VERANO PASADO (1997 – Jennifer Love Hewitt; Ryan Phillippe)' , 
      'AGENTES DEL DESTINO (2011 - Matt Damon; Emily Blunt)' , 
      'SUEÑOS DE LIBERTAD (1994 – Tim Robbins; Morgan Freeman)' , 
      'EL GUARDAESPALDAS (1992 – Whitney Houston; Kevin Costner)' , 
      'DE AMOR Y OTRAS ADICCIONES (2010 – Jake Gyllenhaal; Anne Hathaway)' , 
      'EL CADAVER DE LA NOVIA (2005 – Johnny Depp; Helena Bonham Carter)' , 
      'TARZÁN (1999 – Tony Goldwyn; Glenn Close)' , 
      'GEORGE DE LA SELVA (1997 – Brendan Fraser; Leslie Mann)' , 
      'UNA MENTE BRILLANTE (2001 – Russell Crowe; Jennifer Connelly; Paul Bettany; Ed Harris)' , 
      'UNA ESPOSA DE MENTIRA (2011 – Jennifer Aniston; Adam Sandler; Nicole Kidman)' , 
      'CONFESIONES DE UNA MENTE PELIGROSA (2002 - George Clooney; Drew Barrymore; Julia Roberts)' , 
      'QUÉMESE DESPUÉS DE LEERSE (2008 – Brad Pitt; George Clooney; John Malkovich)' , 
      'MÁTALOS SUAVEMENTE (2012 – Brad Pitt; James Gandolfini)' , 
      'LA GUERRA DE LOS MUNDOS (2005 – Tom Cruise; Dakota Fanning)' , 
      'EL ABOGADO DEL CRIMEN (2013 – Cameron Díaz; Penélope Cruz; Javier Bardem; Brad Pitt)' , 
      'LOS HOMBRES “X” (2000 – Hugh Jackman; Halle Berry; Patrick Stewart)' , 
      'DÍAS DE TRUENO (1990 – Tom Cruise; Nicole Kidman; Robert Duvall)' , 
      'CUESTIÓN DE HONOR (1992 – Tom Cruise; Jack Nicholson; Demi Moore; Kevin Bacon)' , 
      'LEONES POR CORDEROS (2007 – Robert Redford; Tom Cruise; Meryl Streep)' , 
      'LOCOS DE IRA (2003 – Jack Nicholson; Adam Sandler)' , 
      'ANTES DE PARTIR (2007 – Jack Nicholson; Morgan Freeman)' , 
      'ORGULLO Y PREJUICIO (2005 – Keira Knightley; Matthew Macfadyen; Rosamund Pike)' , 
      'EL APARTAMENTO (2004 – Josh Hartnett; Diane Kruger)' , 
      'MUERTE EN UN FUNERAL (2007 – Matthew Macfadyen; Peter Dinklage)' , 
      'CUATRO BODAS Y UN FUNERAL (1994 – Hugh Grant; Andie MacDowell)' , 
      'EL DISCURSO DEL REY (2010 – Colin Firth; Geoffrey Rush; Helena Bonham Carter)' , 
      'ROBIN HOOD (2010 – Russell Crowe; Cate Blanchett)' , 
      'CREPÚSCULO (2008 – Robert Pattinson; Kristen Stewart; Taylor Lautner)' , 
      'HARRY POTTER (2001 – Daniel Radcliffe; Emma Watson; Rupert Grint)' , 
      'EL AVIADOR (2004 – Leonardo DiCaprio; Cate Blanchett; Kate Beckinsale)' , 
      'EL SEÑOR DE LOS ANILLOS (2001 – Elijah Wood; Liv Tyler; Viggo Mortensen; Cate Blanchett)' , 
      'EL VUELO (2012 – Denzel Washington; Kelly Reilly)' , 
      'LA MISIÓN (1986 – Robert De Niro; Jeremy Irons; Liam Neeson)' , 
      'UN GOLPE MAESTRO (2001 – Robert De Niro; Edward Norton; Marlon Brando)' , 
      'MENTE SINIESTRA (2005 – Robert De Niro; Dakota Fanning; Famke Janssen)' , 
      'NOCHE DE FIN DE AÑO (2011 – Robert De Niro; Michelle Pfeiffer; Aston Kutcher; Zac Efron)' , 
      'DOS POR EL DINERO (2005 – Al Pacino; Matthew McConaughy; Rene Russo)' , 
      'LA PRUEBA (2003 – Al Pacino; Colin Farrell)' , 
      'EL SANTO (1997 – Val Kilmer; Elisabeth Shue; Roger Moore)' , 
      'FUEGO CONTRA FUEGO (1995 – Robert De Niro; Al Pacino; Val Kilmer; Natalie Portman)' , 
      'SEÑALES (2002 – Mel Gibson; Joaquin Phoenix)' , 
      'LÍNEA MORTAL (1990 – Kiefer Sutherland; Julia Roberts; Kevin Bacon; William Baldwin)' , 
      'DURMIENDO CON EL ENEMIGO (1991 – Julia Roberts; Patrick Bergin; Kevin Anderson)' , 
      'EL PODER DEL AMOR (1995 - Denis Quaid; Julia Roberts; Robert Duvall)' , 
      'MAMMA MÍA (2008 – Amanda Seyfried; Meryl Streep; Pierce Brosnan; Colin Firth)' , 
      'CIUDAD DE DIOS (2002 – Alexandre Rodriguez; Leandro Firmino; Alice Braga)' , 
      'INFILTRADOS (2006 – Leonardo Di Caprio; Jack Nicholson; Matt Damon; Mark Wahlberg)' , 
      'ESCUELA DE ROCK (2003 – Jack Black; Miranda Cosgrove)' , 
      'LOS RÍOS COLOR PÚRPURA (2000 – Jean Reno; Vincent Cassel)' , 
      'CASABLANCA (1942 – Humphrey Bogart; Ingrid Bergman; Claude Rains)' , 
      'LO QUE EL VIENTO SE LLEVÓ (1939 – Vivien Leigh; Clark Gable; Olivia de Havilland)' , 
      'EL PLANETA DE LOS SIMIOS (2001 – Mark Wahlber; Tim Roth; Helena Bonham Carter)' , 
      'GRAVEDAD (2013 – Sandra Bullock; George Clooney; Ed Harris)' , 
      'EL ZORRO (1998 – Antonio Banderas; Anthony Hopkins; Catherine Zeta-Jones; Matt Letscher)' , 
      'LA MÁSCARA DE HIERRO (1998 – Leonardo Di Caprio; Jeremy Irons; John Malkovich; Gerard Depardieu)' , 
      'PSICOSIS (1960 – Anthony Perkins; Janet Leigh; Vera Miles; Patricia Hitchcock; John Gavin)' , 
      'LA BODA DE MI MEJOR AMIGO (1997 – Julia Roberts; Dermont Mulroney; Cameron Díaz)' , 
      'NOVIA FUGITIVA (1999 – Julia Roberts; Richard Gere; Joan Cusack)' , 
      '¿BAILAMOS? (2004 – Richard Gere; Jennifer Lopez; Susan Sarandon)' , 
      'LA PAREJA DEL AÑO (2001 – Julia Roberts; Catherine Zeta-Jones; John Cusack)' , 
      'LA SONRISA DE MONA LISA (2003 – Julia Roberts; Kirsten Dunst; Maggie Gyllenhaal)' , 
      'LLEVADOS POR EL DESEO (2004 – Clive Owen; Julia Roberts; Natalie Portman; Jude Law)' , 
      'JUEGOS DE PODER (2007 – Tom Hanks; Julia Roberts; Philip Seymour; Amy Adams; Emily Blunt)' , 
      'DÍA DE LOS ENAMORADOS (2010 – Ashton Kutcher; Julia Roberts; Anne Hattaway; Jessica Alba; Bradley Cooper; Patrick Dempsey; Jamie Foxx)' , 
      'COMER, REZAR, AMAR (2010 – Julia Roberts; Javier Bardem; James Franco)' , 
      'ESPEJITO, ESPEJITO (2012 – Julia Roberts; Armie Hammer; Sean Bean; Lily Collins)' , 
      'OJOS BIEN CERRADOS (1999 – Tom Cruise; Nicole Kidman)' , 
      'EL DISCURSO DEL REY (2010 – Colin Firth; Helena Bonham Carter; Geoffrey Rush)' , 
      'LOS TRES MOSQUETEROS (1993 – Charlie Sheen; Kiefer Sutherland; Chris O’Donnell)' , 
      'QUIERO MATAR A MI JEFE (2011 – Jason Bateman; Kevin Spacey; Jennifer Aniston)' , 
      '¿QUÉ PASÓ AYER? (2009 – Zach Galifianakis; Bradley Cooper; Ed Helms)' , 
      '¿QUIÉN ENGAÑÓ A ROGER RABBIT? (1988 – Bob Hoskins; Christopher Lloyd; Joanna Cassidy)' , 
      'HACIA RUTAS SALVAJES (2007 – Emile Hirsch; Kristen Stewart; Vince Vaughn)' , 
      'ROBOCOP (1987 – Peter Weller; Nancy Allen; Ronny Cox)' , 
      'KING KONG (2005 – Naomi Watts; Adrien Brody; Jack Black; Peter Jackson)' , 
      'TITANIC (1997 – Leonardo DiCaprio; Kate Winslet)' , 
      'DIARIO DE UNA PASIÓN (2004 – Rachel McAdams; Ryan Gosling; James Marsden)' , 
      'EL PIANISTA (2002 – Adrien Brody; Emilia Fox; Frank Finley)' , 
      'EL PACIENTE INGLÉS (1996 – Ralph Fiennes; Willem Dafoe; Juliette Binoche)' , 
      'LAS HORAS (2003 – Nicole Kidman; Meryl Streep; Julianne Moore; Ed Harris)' , 
      'LA INTÉRPRETE (2005 – Sean Penn; Nicole Kidman)' , 
      'LA FUERZA DE UNO (1992 – Morgan Freeman; Stephen Dorff; Daniel Craig)' , 
      'LA INVASIÓN (2007 – Daniel Craig; Nicole Kidman; Jeremy Northam)' , 
      'PODER QUE MATA (2010 – Naomi Watts; Sean Penn)' , 
      'NADA MÁS QUE LA VERDAD (2008 – Kate Beckinsale; Matt Dillon)' , 
      '21 GRAMOS (2003 – Naomi Watts; Sean Penn; Benicio del Toro)' , 
      'BAJO AMENAZA (2010 – Nicolas Cage; Nicole Kidman)' , 
      'EL CENTINELA (2006 – Michael Douglas; Kiefer Sutherland; Eva Longoria; Kim Basinger)' , 
      'LA NOCHE MÁS OSCURA (2012 – Chris Pratt; Jason Clarke; Jessica Chastain)' , 
      'NI UNA PALABRA (2001 – Michael Douglas; Brittany Murphy; Sean Bean: Famke Janssen)' , 
      'UN CRIMEN PERFECTO (1998 – Michael Douglas; Gwyneth Paltrow; Viggo Mortensen)' , 
      'EN LA LÍNEA DE FUEGO (1993 – Clint Eastwood; John Malkovich; Rene Russo)' , 
      'JUEGO DE ESPÍAS (2001 – Robert Redford; Brad Pitt)' , 
      'NUEVE VIDAS (2005 – Glenn Close; Dakota Fanning)' , 
      'MADRE E HIJA (2009 – Naomi Watts; Samuel Jackson)' , 
      'EL REPARTIDOR DE DIARIOS (2012 – Matthew McConaughy; Nicole Kidman; Zac Effron; John Cusack)' , 
      'EL ESCRITOR OCULTO (2010 – Pierce Brosnan; Ewan McGregor; Olivia Williams)' , 
      'CRIMEN DE AUTOR (2006 – Fanny Ardant; Dominique Pinon; Audrey Dana)' , 
      'LA PISCINA (2003 – Ludivine Sagnier; Charlotte Rampling)' , 
      'ANTES DE DESPERTAR (2014 – Colin Firth; Nicole Kidman; Mark Strong)' , 
      'LA HIJA DEL PRESIDENTE (2004 – Mandy Moore; Matthew Goode)' , 
      'DOCTOR “T” Y LAS MUJERES (2000 – Richard Gere; Helen Hunt; Kate Hudson; Liv Tyler; Farrah Fawcett)' , 
      'LA LLAVE MAESTRA (2005 – Kate Hudson; Gena Rowlands; John Hurt)' , 
      'AMOR Y TESORO (2008 – Matthew McConaughy; Kate Hudson; Donald Sutherland)' , 
      'EL DIABLO BAJO LA PIEL (2010 – Jessica Alba; Kate Hudson; Casey Affleck)' , 
      'NO ME QUITES A MI NOVIO (2011 – Kate Hudson; John Krasinski)' , 
      'TODO UN PARTO (2010 – Robert Downey Jr; Zach Galifianakis; Michelle Monaghan; Jamie Foxx)' , 
      'LA JOVEN VICTORIA (2009 – Emily Blunt; Paul Bettany; Rupert Friend)' , 
      'EL APRENDIZ DE BRUJO (2010 – Nicolas Cage; Monica Bellucci)' , 
      'TRES SON MULTITUD (2006 – Owen Wilson; Kate Hudson; Matt Dillon)' , 
      'LA DUQUEZA (2008 – Keira Knightley; Ralph Fiennes)' , 
      'SÓLO UN SUEÑO (2008 – Kate Winslet; Leonardo DiCaprio)' , 
      'LAS DOS CARAS DE LA LEY (2008 – Robert De Niro; Al Pacino)' , 
      'LEJOS DEL PARAÍSO (2002 – Dennis Quaid; Julianne Moore)' , 
      'YO NO ESTOY AQUÍ (2007 – Christian Bale; Cate Blanchett; Richard Gere; Heath Ledger)' , 
      'EL HOMBRE DE LA BOLSA (2005 – Barry Watson; Emily Deschanel)' , 
      'LA TORMENTA DE HIELO (1997 – Elijah Wood; Tobey Maguire; Christina Ricci)' , 
      'CAPITÁN DE MAR Y GUERRA (2003 – Russell Crowe; Paul Bettany)' , 
      'ALIEN VERSUS DEPREDADOR (2004 – Ewen Bremner; Raoul Bova)' , 
      'MOULIN ROUGE (2001 – Ewan McGregor; Nicole Kidman)' , 
      'EN SUS ZAPATOS (2005 – Cameron Díaz; Toni Collette)' , 
      'EL ESPANTA TIBURONES (2004 – Angelina Jolie; Robert De Niro; Will Smith; Jack Black)' , 
      'EN BUSCA DE LA FELICIDAD (2006 – Will Smith; Jaden Smith)' , 
      'SIETE ALMAS (2008 – Will Smith; Rosario Dawson; Woody Harrelson)' , 
      'EL NUEVO SUEÑO AMERICANO (2000 – Ben Affleck; Vin Diesel; Giovanni Ribisi)' , 
      'ENEMIGO PÚBLICO (1998 – Will Smith; Gene Hackman; Jon Voight)' , 
      'CONTROL TOTAL (2008 – Shia LeBeouf; Michelle Monaghan; Rosario Dawson)' , 
      'NEGRO Y BLANCO (1999 – Robert Downey Jr; Jared Leto; Brooke Shields)' , 
      'PROTEGIENDO AL ENEMIGO (2012 - Denzel Washington; Ryan Reynolds)' , 
      'IMPARABLE (2010 – Denzel Washington; Chris Pine)' , 
      'EL LIBRO DE LOS SECRETOS (2010 – Denzel Washington; Gary Oldman)' , 
      'RESCATE DEL METRO 123 (2009 – Denzel Washington; John Travolta)' , 
      'GRANDES DEBATES (2007 - Denzel Washington)' , 
      'GANGSTER AMERICANO (2007 - Denzel Washington; Russell Crowe)' , 
      'EL PLAN PERFECTO (2006 - Denzel Washington; Clive Owen; Jodie Foster)' , 
      'EL EMBAJADOR DEL MIEDO (2004 - Denzel Washington; Meryl Streep)' , 
      'HOMBRE EN LLAMAS (2004 - Denzel Washington; Dakota Fanning; Christopher Walken)' , 
      'TIEMPO LÍMITE (2003 - Denzel Washington; Eva Mendez)' , 
      'DÍA DE ENTRENAMIENTO (2001 - Denzel Washington; Ethan Hawke; Eva Mendez)' , 
      'EL COLECCIONISTA DE HUESOS (1999 – Denzel Washington; Angelina Jolie)' , 
      'CONTRA EL ENEMIGO (1998 - Denzel Washington; Bruce Willis)' , 
      'MAREA ROJA (1995 – Denzel Washington; Viggo Mortensen)' , 
      'EL INFORME PELÍCANO (1993 - Denzel Washington; Julia Roberts)' , 
      'TESTIGO EN PELIGRO (1985 - Harrison Ford; Viggo Mortensen)' , 
      'PÁNICO EN EL TÚNEL (1996 - Viggo Mortensen; Sylvester Stallone)' , 
      '28 DÍAS (2000 - Viggo Mortensen; Sandra Bullock)' , 
      'OCÉANO DE FUEGO (2004 – Omar Shariff; Viggo Mortensen)' , 
      'UNA HISTORIA VIOLENTA (2005 – Viggo Mortensen; María Bello)' , 
      'LA CARRETERA (2009 - Viggo Mortensen; Robert Duvall)' , 
      'EN EL CAMINO (2012 – Viggo Mortensen; Amy Adams)' , 
      'COWBOYS VERSUS ALIENS (2011 – Daniel Craig; Olivia Wilde; Harrison Ford)' , 
      'DEPARTAMENTO DE HOMICIDIOS (2003 – Harrison Ford; Josh Hartnett)' , 
      'DESTINOS CRUZADOS (1999 – Harrison Ford; Dennis Haysbert)' , 
      'SEIS DÍAS, SIETE NOCHES (1998 – Harrison Ford)' , 
      'AVIÓN PRESIDENCIAL (1997 – Harrison Ford; Gary Oldman; Glenn Close)' , 
      'EL FUGITIVO (1993 – Harrison Ford; Tomy Lee Jones)' , 
      'EL SUSTITUTO (2008 – Angelina Jolie; John Malkovich)' , 
      '60 SEGUNDOS (2000 - Nicolas Cage; Angelina Jolie; Robert Duvall)' , 
      'FUERA DE CONTROL (1999 – Angelina Jolie; John Cusack; Cate Blanchett)' , 
      'JUGANDO CON EL CORAZÓN (1998 -  Sean Connery; Angelina Jolie)' , 
      'LA CHICA DEL DRAGÓN TATUADO (2011 – Daniel Craig)' , 
      'DETRÁS DE LAS PAREDES (2011 – Daniel Craig; Rachel Weisz; Naomi Watts)' , 
      'DESAFÍO (2008 - Daniel Craig; Liev Schreiber)' , 
      'LA BRÚJULA DORADA (2007 - Daniel Craig; Nicole Kidman)' , 
      '1000 PALABRAS (2012 - Eddie Murphy)' , 
      'CACERÍA DE BRUJAS (2011 - Nicolas Cage; Ron Perlman)' , 
      'EL VIDENTE (2007 – Nicolas Cage; Julianne Moore)' , 
      'LAS TORRES GEMELAS (2006 - Nicholas Cage; María Bello)' , 
      'MAGIA A LA LUZ DE LA LUNA (2014 – Emma Stone; Colin Firth)' , 
      'AMOR Y MUERTE (2006 - Scarlett Johansson; Woody Allen)' , 
      'LADRONES DE MEDIO PELO (2000 – Woody Allen; Hugh Grant)' , 
      'EL GRAN AMANTE (1999 - Sean Penn; Uma Thurman)' , 
      'MARIDOS Y ESPOSAS (1992 – Woody Allen; Mia Farrow)' , 
      'UNA FAMILIA CON CLASE (2008 – Colin Firth; Jessica Biel)' , 
      'LA NIÑERA MÁGICA (2005 – Colin Firth; Ema Thompson)' , 
      'EL DIARIO DE BRIDGET JONES (2001 – Colin Firth; Reneé Zellweger; Hugh Grant)' , 
      'CRIMEN PERFECTO (2007 – Ryan Gosgling; Anthony Hopkins)' , 
      'TODOS LOS HOMBRES DEL REY (2006 – Sean Penn; Jude Law; Kate Winslet; Anthony Hopkins)' , 
      'AL FILO DEL PELIGRO (1997 – Alec Baldwin; Anthony Hopkins)' , 
      'AMISTAD (1997 – Anthony Hopkins; Matthew McConaughey; Morgan Freeman)' , 
      'SUPERMAN, EL HOMBRE DE ACERO (2013 – Henry Cavill; Amy Adams; Kevin Costner)' , 
      'SÓLO TRES DÍAS (2010 – Russell Crowe; Elizabeth Banks; Liam Neeson; Olivia Wilde)' , 
      'LA SOMBRA DEL PODER (2009 – Russell Crowe; Ben Affleck; Rachel McAdams)' , 
      'RED DE MENTIRAS (2008 – Rusell Crowe; Leonardo DiCaprio)' , 
      'DIAMANTE DE SANGRE (2006 - Leonardo DiCaprio; Jennifer Connelly)' , 
      'PRUEBA DE VIDA (2000 – Russell Crowe; Meg Ryan)' , 
      'EL ORIGEN DE LOS GUARDIANES (2012 – Alec Baldwin; Jude Law; Chris Pine)' , 
      'EL DESCANSO (2006 – Jude Law; Cameron Díaz; Kate Winslet; Jack Black)' , 
      'EL LECTOR (2008 – Kate Winslet; Ralph Fiennes)' , 
      'LO QUE EL AGUA SE LLEVÓ (2006 – Hugh Jackman; Kate Winslet)' , 
      'LA DAMA Y EL VAGABUNDO (1955)' , 
      'LA SIRENITA (1989)' , 
      'LA BELLA DURMIENTE (1959)' , 
      'DUMBO (1941)' , 
      'BUSCANDO A NEMO (2003 – Willem Dafoe; Ellen DeGeneres; Geoffrey Rush)' , 
      'FIEBRE DE SÁBADO POR LA NOCHE (1977 – John Travolta; Karen Lynn Gorney)' , 
      'ENREDADOS (2010 – Mandy Moore; Zachary Levi)' , 
      'EL LIBRO DE LA SELVA (1967)' , 
      'PINOCHO (1940)' , 
      'FANTASÍA (1940)' , 
      '101 DÁLMATAS (1961)' , 
      'LOS INCREÍBLES (2004)' , 
      'BICHOS (1998)' , 
      'VALIENTE (2012)' , 
      'TIERRA DE OSOS (2012 - Emma Thompson; Billy Connolly)' , 
      'ENCANTADA (2007 – Amy Adams; Patrick Dempsey; James Marsden)' , 
      'EL PLANETA DEL TESORO (2002)' , 
      'DINOSAURIO (2000)' , 
      'CUENTOS QUE NO SON CUENTOS (2008 – Adam Sandler; Courtney Cox)' , 
      'EL EXPRESO POLAR (2004 – Tom Hanks; Michael Jeter)' , 
      'EL CALDERO MÁGICO (1985 – John Hurt; Susan Sheridan)' , 
      'EL ZORRO Y EL SABUESO (1981 – Mickey Rooney; Kurt Russell)' , 
      'ENTRENANDO A PAPÁ (2007 – Dwayne Johnson; Roselyn Sánchez)' , 
      'LA ESPADA EN LA PIEDRA (1963)' , 
      'LA FAMILIA DEL FUTURO (2007 – Tom Selleck; Jordan Fry)' , 
      'LA PRINCESA Y EL SAPO (2009 – Anika Rose; Ophra Winfrey)' , 
      'MARTE NECESITA MAMÁS (2001 – Joan Cusack; Seth Green)' , 
      'UN VIERNES DE LOCOS (2003 – Lindsay Lohan; Jamie Lee Curtis; Mark Harmon)' , 
      'UNA NIÑERA A PRUEBA DE BALAS (2005 – Vin Diesel; Lauren Graham)' , 
      'VACAS VAQUERAS (2004 – Roseanne Barr; Cuba Gooding Jr.)'  
    ]
    
    var cant = lista.length;
    var peli = Math.floor(Math.random() * cant);
    return lista[peli];
    
}
    
function mostrarPeli() {
    
    t_peli.innerHTML = peliculas();
    t_peli.style.visibility = "visible";
} 